/*
 * Copyright 2021, TAUTUA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.tautua.jwkhtmltox.jna;
import com.sun.jna.*;
import com.sun.jna.ptr.PointerByReference;

import java.nio.ByteBuffer;

/**
 * JNA Wrapper for library <b>WebKitHtmlToPdf</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface WebKitHtmlToPdfLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "wkhtmltox";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(WebKitHtmlToPdfLibrary.JNA_LIBRARY_NAME);
	public static final WebKitHtmlToPdfLibrary INSTANCE = (WebKitHtmlToPdfLibrary)Native.loadLibrary(WebKitHtmlToPdfLibrary.JNA_LIBRARY_NAME, WebKitHtmlToPdfLibrary.class);
	/** <i>native declaration : src/main/c/wkhtmltox/pdf.h:6</i> */
	public interface wkhtmltopdf_str_callback extends Callback {
		void apply(Pointer converter, String str);
	};
	/** <i>native declaration : src/main/c/wkhtmltox/pdf.h:7</i> */
	public interface wkhtmltopdf_int_callback extends Callback {
		void apply(Pointer converter, int val);
	};
	/** <i>native declaration : src/main/c/wkhtmltox/pdf.h:8</i> */
	public interface wkhtmltopdf_void_callback extends Callback {
		void apply(Pointer converter);
	};
	/**
	 * Original signature : <code>int wkhtmltopdf_init(int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:10</i>
	 */
	int wkhtmltopdf_init(int use_graphics);
	/**
	 * Original signature : <code>int wkhtmltopdf_deinit()</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:12</i>
	 */
	int wkhtmltopdf_deinit();
	/**
	 * Original signature : <code>int wkhtmltopdf_extended_qt()</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:14</i>
	 */
	int wkhtmltopdf_extended_qt();
	/**
	 * Original signature : <code>char* wkhtmltopdf_version()</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:16</i>
	 */
	Pointer wkhtmltopdf_version();
	/**
	 * Original signature : <code>wkhtmltopdf_global_settings* wkhtmltopdf_create_global_settings()</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:18</i>
	 */
	PointerByReference wkhtmltopdf_create_global_settings();
	/**
	 * Original signature : <code>void wkhtmltopdf_destroy_global_settings(wkhtmltopdf_global_settings*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:20</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_destroy_global_settings(PointerByReference)} instead
	 */
	@Deprecated 
	void wkhtmltopdf_destroy_global_settings(Pointer wkhtmltopdf_global_settingsPtr1);
	/**
	 * Original signature : <code>void wkhtmltopdf_destroy_global_settings(wkhtmltopdf_global_settings*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:20</i>
	 */
	void wkhtmltopdf_destroy_global_settings(PointerByReference wkhtmltopdf_global_settingsPtr1);
	/**
	 * Original signature : <code>wkhtmltopdf_object_settings* wkhtmltopdf_create_object_settings()</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:22</i>
	 */
	PointerByReference wkhtmltopdf_create_object_settings();
	/**
	 * Original signature : <code>void wkhtmltopdf_destroy_object_settings(wkhtmltopdf_object_settings*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:24</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_destroy_object_settings(PointerByReference)} instead
	 */
	@Deprecated 
	void wkhtmltopdf_destroy_object_settings(Pointer wkhtmltopdf_object_settingsPtr1);
	/**
	 * Original signature : <code>void wkhtmltopdf_destroy_object_settings(wkhtmltopdf_object_settings*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:24</i>
	 */
	void wkhtmltopdf_destroy_object_settings(PointerByReference wkhtmltopdf_object_settingsPtr1);
	/**
	 * Original signature : <code>int wkhtmltopdf_set_global_setting(wkhtmltopdf_global_settings*, const char*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:26</i><br>
	 * @deprecated use the safer methods {@link #wkhtmltopdf_set_global_setting(PointerByReference, String, String)} and {@link #wkhtmltopdf_set_global_setting(PointerByReference, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int wkhtmltopdf_set_global_setting(Pointer settings, Pointer name, Pointer value);
	/**
	 * Original signature : <code>int wkhtmltopdf_set_global_setting(wkhtmltopdf_global_settings*, const char*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:26</i>
	 */
	int wkhtmltopdf_set_global_setting(PointerByReference settings, String name, String value);
	/**
	 * Original signature : <code>int wkhtmltopdf_set_global_setting(wkhtmltopdf_global_settings*, const char*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:26</i>
	 */
	int wkhtmltopdf_set_global_setting(PointerByReference settings, Pointer name, Pointer value);
	/**
	 * Original signature : <code>int wkhtmltopdf_get_global_setting(wkhtmltopdf_global_settings*, const char*, char*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:28</i><br>
	 * @deprecated use the safer methods {@link #wkhtmltopdf_get_global_setting(PointerByReference, String, ByteBuffer, int)} and {@link #wkhtmltopdf_get_global_setting(PointerByReference, Pointer, Pointer, int)} instead
	 */
	@Deprecated 
	int wkhtmltopdf_get_global_setting(Pointer settings, Pointer name, Pointer value, int vs);
	/**
	 * Original signature : <code>int wkhtmltopdf_get_global_setting(wkhtmltopdf_global_settings*, const char*, char*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:28</i>
	 */
	int wkhtmltopdf_get_global_setting(PointerByReference settings, String name, ByteBuffer value, int vs);
	/**
	 * Original signature : <code>int wkhtmltopdf_get_global_setting(wkhtmltopdf_global_settings*, const char*, char*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:28</i>
	 */
	int wkhtmltopdf_get_global_setting(PointerByReference settings, Pointer name, Pointer value, int vs);
	/**
	 * Original signature : <code>int wkhtmltopdf_set_object_setting(wkhtmltopdf_object_settings*, const char*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:30</i><br>
	 * @deprecated use the safer methods {@link #wkhtmltopdf_set_object_setting(PointerByReference, String, String)} and {@link #wkhtmltopdf_set_object_setting(PointerByReference, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int wkhtmltopdf_set_object_setting(Pointer settings, Pointer name, Pointer value);
	/**
	 * Original signature : <code>int wkhtmltopdf_set_object_setting(wkhtmltopdf_object_settings*, const char*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:30</i>
	 */
	int wkhtmltopdf_set_object_setting(PointerByReference settings, String name, String value);
	/**
	 * Original signature : <code>int wkhtmltopdf_set_object_setting(wkhtmltopdf_object_settings*, const char*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:30</i>
	 */
	int wkhtmltopdf_set_object_setting(PointerByReference settings, Pointer name, Pointer value);
	/**
	 * Original signature : <code>int wkhtmltopdf_get_object_setting(wkhtmltopdf_object_settings*, const char*, char*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:32</i><br>
	 * @deprecated use the safer methods {@link #wkhtmltopdf_get_object_setting(PointerByReference, String, ByteBuffer, int)} and {@link #wkhtmltopdf_get_object_setting(PointerByReference, Pointer, Pointer, int)} instead
	 */
	@Deprecated 
	int wkhtmltopdf_get_object_setting(Pointer settings, Pointer name, Pointer value, int vs);
	/**
	 * Original signature : <code>int wkhtmltopdf_get_object_setting(wkhtmltopdf_object_settings*, const char*, char*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:32</i>
	 */
	int wkhtmltopdf_get_object_setting(PointerByReference settings, String name, ByteBuffer value, int vs);
	/**
	 * Original signature : <code>int wkhtmltopdf_get_object_setting(wkhtmltopdf_object_settings*, const char*, char*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:32</i>
	 */
	int wkhtmltopdf_get_object_setting(PointerByReference settings, Pointer name, Pointer value, int vs);
	/**
	 * Original signature : <code>wkhtmltopdf_converter* wkhtmltopdf_create_converter(wkhtmltopdf_global_settings*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:34</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_create_converter(PointerByReference)} instead
	 */
	@Deprecated 
	PointerByReference wkhtmltopdf_create_converter(Pointer settings);
	/**
	 * Original signature : <code>wkhtmltopdf_converter* wkhtmltopdf_create_converter(wkhtmltopdf_global_settings*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:34</i>
	 */
	PointerByReference wkhtmltopdf_create_converter(PointerByReference settings);
	/**
	 * Original signature : <code>void wkhtmltopdf_destroy_converter(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:36</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_destroy_converter(PointerByReference)} instead
	 */
	@Deprecated 
	void wkhtmltopdf_destroy_converter(Pointer converter);
	/**
	 * Original signature : <code>void wkhtmltopdf_destroy_converter(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:36</i>
	 */
	void wkhtmltopdf_destroy_converter(PointerByReference converter);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_warning_callback(wkhtmltopdf_converter*, wkhtmltopdf_str_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:38</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_set_warning_callback(PointerByReference, wkhtmltopdf_str_callback)} instead
	 */
	@Deprecated 
	void wkhtmltopdf_set_warning_callback(Pointer converter, wkhtmltopdf_str_callback cb);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_warning_callback(wkhtmltopdf_converter*, wkhtmltopdf_str_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:38</i>
	 */
	void wkhtmltopdf_set_warning_callback(PointerByReference converter, wkhtmltopdf_str_callback cb);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_error_callback(wkhtmltopdf_converter*, wkhtmltopdf_str_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:40</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_set_error_callback(PointerByReference, wkhtmltopdf_str_callback)} instead
	 */
	@Deprecated 
	void wkhtmltopdf_set_error_callback(Pointer converter, wkhtmltopdf_str_callback cb);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_error_callback(wkhtmltopdf_converter*, wkhtmltopdf_str_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:40</i>
	 */
	void wkhtmltopdf_set_error_callback(PointerByReference converter, wkhtmltopdf_str_callback cb);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_phase_changed_callback(wkhtmltopdf_converter*, wkhtmltopdf_void_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:42</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_set_phase_changed_callback(PointerByReference, wkhtmltopdf_void_callback)} instead
	 */
	@Deprecated 
	void wkhtmltopdf_set_phase_changed_callback(Pointer converter, wkhtmltopdf_void_callback cb);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_phase_changed_callback(wkhtmltopdf_converter*, wkhtmltopdf_void_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:42</i>
	 */
	void wkhtmltopdf_set_phase_changed_callback(PointerByReference converter, wkhtmltopdf_void_callback cb);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_progress_changed_callback(wkhtmltopdf_converter*, wkhtmltopdf_int_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:44</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_set_progress_changed_callback(PointerByReference, wkhtmltopdf_int_callback)} instead
	 */
	@Deprecated 
	void wkhtmltopdf_set_progress_changed_callback(Pointer converter, wkhtmltopdf_int_callback cb);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_progress_changed_callback(wkhtmltopdf_converter*, wkhtmltopdf_int_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:44</i>
	 */
	void wkhtmltopdf_set_progress_changed_callback(PointerByReference converter, wkhtmltopdf_int_callback cb);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_finished_callback(wkhtmltopdf_converter*, wkhtmltopdf_int_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:46</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_set_finished_callback(PointerByReference, wkhtmltopdf_int_callback)} instead
	 */
	@Deprecated 
	void wkhtmltopdf_set_finished_callback(Pointer converter, wkhtmltopdf_int_callback cb);
	/**
	 * Original signature : <code>void wkhtmltopdf_set_finished_callback(wkhtmltopdf_converter*, wkhtmltopdf_int_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:46</i>
	 */
	void wkhtmltopdf_set_finished_callback(PointerByReference converter, wkhtmltopdf_int_callback cb);
	/**
	 * CAPI(void) wkhtmltopdf_cancel(wkhtmltopdf_converter * converter);<br>
	 * Original signature : <code>int wkhtmltopdf_convert(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:51</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_convert(PointerByReference)} instead
	 */
	@Deprecated 
	int wkhtmltopdf_convert(Pointer converter);
	/**
	 * CAPI(void) wkhtmltopdf_cancel(wkhtmltopdf_converter * converter);<br>
	 * Original signature : <code>int wkhtmltopdf_convert(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:51</i>
	 */
	int wkhtmltopdf_convert(PointerByReference converter);
	/**
	 * Original signature : <code>void wkhtmltopdf_add_object(wkhtmltopdf_converter*, wkhtmltopdf_object_settings*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:53</i><br>
	 * @deprecated use the safer methods {@link #wkhtmltopdf_add_object(PointerByReference, PointerByReference, String)} and {@link #wkhtmltopdf_add_object(PointerByReference, PointerByReference, Pointer)} instead
	 */
	@Deprecated 
	void wkhtmltopdf_add_object(Pointer converter, Pointer setting, Pointer data);
	/**
	 * Original signature : <code>void wkhtmltopdf_add_object(wkhtmltopdf_converter*, wkhtmltopdf_object_settings*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:53</i>
	 */
	void wkhtmltopdf_add_object(PointerByReference converter, PointerByReference setting, String data);
	/**
	 * Original signature : <code>void wkhtmltopdf_add_object(wkhtmltopdf_converter*, wkhtmltopdf_object_settings*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:53</i>
	 */
	void wkhtmltopdf_add_object(PointerByReference converter, PointerByReference setting, Pointer data);
	/**
	 * Original signature : <code>int wkhtmltopdf_current_phase(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:55</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_current_phase(PointerByReference)} instead
	 */
	@Deprecated 
	int wkhtmltopdf_current_phase(Pointer converter);
	/**
	 * Original signature : <code>int wkhtmltopdf_current_phase(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:55</i>
	 */
	int wkhtmltopdf_current_phase(PointerByReference converter);
	/**
	 * Original signature : <code>int wkhtmltopdf_phase_count(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:57</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_phase_count(PointerByReference)} instead
	 */
	@Deprecated 
	int wkhtmltopdf_phase_count(Pointer converter);
	/**
	 * Original signature : <code>int wkhtmltopdf_phase_count(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:57</i>
	 */
	int wkhtmltopdf_phase_count(PointerByReference converter);
	/**
	 * Original signature : <code>char* wkhtmltopdf_phase_description(wkhtmltopdf_converter*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:59</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_phase_description(PointerByReference, int)} instead
	 */
	@Deprecated 
	Pointer wkhtmltopdf_phase_description(Pointer converter, int phase);
	/**
	 * Original signature : <code>char* wkhtmltopdf_phase_description(wkhtmltopdf_converter*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:59</i>
	 */
	Pointer wkhtmltopdf_phase_description(PointerByReference converter, int phase);
	/**
	 * Original signature : <code>char* wkhtmltopdf_progress_string(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:61</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_progress_string(PointerByReference)} instead
	 */
	@Deprecated 
	Pointer wkhtmltopdf_progress_string(Pointer converter);
	/**
	 * Original signature : <code>char* wkhtmltopdf_progress_string(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:61</i>
	 */
	Pointer wkhtmltopdf_progress_string(PointerByReference converter);
	/**
	 * Original signature : <code>int wkhtmltopdf_http_error_code(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:63</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_http_error_code(PointerByReference)} instead
	 */
	@Deprecated 
	int wkhtmltopdf_http_error_code(Pointer converter);
	/**
	 * Original signature : <code>int wkhtmltopdf_http_error_code(wkhtmltopdf_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:63</i>
	 */
	int wkhtmltopdf_http_error_code(PointerByReference converter);
	/**
	 * Original signature : <code>long wkhtmltopdf_get_output(wkhtmltopdf_converter*, const unsigned char**)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:65</i><br>
	 * @deprecated use the safer method {@link #wkhtmltopdf_get_output(PointerByReference, PointerByReference)} instead
	 */
	@Deprecated 
	NativeLong wkhtmltopdf_get_output(Pointer converter, PointerByReference charPtrPtr1);
	/**
	 * Original signature : <code>long wkhtmltopdf_get_output(wkhtmltopdf_converter*, const unsigned char**)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/pdf.h:65</i>
	 */
	NativeLong wkhtmltopdf_get_output(PointerByReference converter, PointerByReference charPtrPtr1);
	public static class wkhtmltopdf_global_settings extends PointerType {
		public wkhtmltopdf_global_settings(Pointer address) {
			super(address);
		}
		public wkhtmltopdf_global_settings() {
			super();
		}
	};
	public static class wkhtmltopdf_object_settings extends PointerType {
		public wkhtmltopdf_object_settings(Pointer address) {
			super(address);
		}
		public wkhtmltopdf_object_settings() {
			super();
		}
	};
	public static class wkhtmltopdf_converter extends PointerType {
		public wkhtmltopdf_converter(Pointer address) {
			super(address);
		}
		public wkhtmltopdf_converter() {
			super();
		}
	};
}
