/*
 * Copyright 2021, TAUTUA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.tautua.jwkhtmltox.jna;

import com.sun.jna.*;
import com.sun.jna.ptr.PointerByReference;

import java.nio.ByteBuffer;

/**
 * JNA Wrapper for library <b>WebKitHtmlToImage</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface WebKitHtmlToImageLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "wkhtmltox";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(WebKitHtmlToImageLibrary.JNA_LIBRARY_NAME);
	public static final WebKitHtmlToImageLibrary INSTANCE = (WebKitHtmlToImageLibrary)Native.loadLibrary(WebKitHtmlToImageLibrary.JNA_LIBRARY_NAME, WebKitHtmlToImageLibrary.class);
	/** <i>native declaration : src/main/c/wkhtmltox/image.h:4</i> */
	public interface wkhtmltoimage_str_callback extends Callback {
		void apply(Pointer converter, String str);
	};
	/** <i>native declaration : src/main/c/wkhtmltox/image.h:5</i> */
	public interface wkhtmltoimage_int_callback extends Callback {
		void apply(Pointer converter, int val);
	};
	/** <i>native declaration : src/main/c/wkhtmltox/image.h:6</i> */
	public interface wkhtmltoimage_void_callback extends Callback {
		void apply(Pointer converter);
	};
	/**
	 * Original signature : <code>int wkhtmltoimage_init(int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:8</i>
	 */
	int wkhtmltoimage_init(int use_graphics);
	/**
	 * Original signature : <code>int wkhtmltoimage_deinit()</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:10</i>
	 */
	int wkhtmltoimage_deinit();
	/**
	 * Original signature : <code>int wkhtmltoimage_extended_qt()</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:12</i>
	 */
	int wkhtmltoimage_extended_qt();
	/**
	 * Original signature : <code>char* __stdcallwkhtmltoimage_version()</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:14</i>
	 */
	Pointer __stdcallwkhtmltoimage_version();
	/**
	 * Original signature : <code>wkhtmltoimage_global_settings* wkhtmltoimage_create_global_settings()</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:16</i>
	 */
	PointerByReference wkhtmltoimage_create_global_settings();
	/**
	 * Original signature : <code>int wkhtmltoimage_set_global_setting(wkhtmltoimage_global_settings*, const char*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:18</i><br>
	 * @deprecated use the safer methods {@link #wkhtmltoimage_set_global_setting(PointerByReference, String, String)} and {@link #wkhtmltoimage_set_global_setting(PointerByReference, Pointer, Pointer)} instead
	 */
	@Deprecated 
	int wkhtmltoimage_set_global_setting(Pointer settings, Pointer name, Pointer value);
	/**
	 * Original signature : <code>int wkhtmltoimage_set_global_setting(wkhtmltoimage_global_settings*, const char*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:18</i>
	 */
	int wkhtmltoimage_set_global_setting(PointerByReference settings, String name, String value);
	/**
	 * Original signature : <code>int wkhtmltoimage_set_global_setting(wkhtmltoimage_global_settings*, const char*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:18</i>
	 */
	int wkhtmltoimage_set_global_setting(PointerByReference settings, Pointer name, Pointer value);
	/**
	 * Original signature : <code>int wkhtmltoimage_get_global_setting(wkhtmltoimage_global_settings*, const char*, char*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:20</i><br>
	 * @deprecated use the safer methods {@link #wkhtmltoimage_get_global_setting(PointerByReference, String, ByteBuffer, int)} and {@link #wkhtmltoimage_get_global_setting(PointerByReference, Pointer, Pointer, int)} instead
	 */
	@Deprecated 
	int wkhtmltoimage_get_global_setting(Pointer settings, Pointer name, Pointer value, int vs);
	/**
	 * Original signature : <code>int wkhtmltoimage_get_global_setting(wkhtmltoimage_global_settings*, const char*, char*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:20</i>
	 */
	int wkhtmltoimage_get_global_setting(PointerByReference settings, String name, ByteBuffer value, int vs);
	/**
	 * Original signature : <code>int wkhtmltoimage_get_global_setting(wkhtmltoimage_global_settings*, const char*, char*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:20</i>
	 */
	int wkhtmltoimage_get_global_setting(PointerByReference settings, Pointer name, Pointer value, int vs);
	/**
	 * Original signature : <code>wkhtmltoimage_converter* wkhtmltoimage_create_converter(wkhtmltoimage_global_settings*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:22</i><br>
	 * @deprecated use the safer methods {@link #wkhtmltoimage_create_converter(PointerByReference, String)} and {@link #wkhtmltoimage_create_converter(PointerByReference, Pointer)} instead
	 */
	@Deprecated 
	PointerByReference wkhtmltoimage_create_converter(Pointer settings, Pointer data);
	/**
	 * Original signature : <code>wkhtmltoimage_converter* wkhtmltoimage_create_converter(wkhtmltoimage_global_settings*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:22</i>
	 */
	PointerByReference wkhtmltoimage_create_converter(PointerByReference settings, String data);
	/**
	 * Original signature : <code>wkhtmltoimage_converter* wkhtmltoimage_create_converter(wkhtmltoimage_global_settings*, const char*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:22</i>
	 */
	PointerByReference wkhtmltoimage_create_converter(PointerByReference settings, Pointer data);
	/**
	 * Original signature : <code>void wkhtmltoimage_destroy_converter(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:24</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_destroy_converter(PointerByReference)} instead
	 */
	@Deprecated 
	void wkhtmltoimage_destroy_converter(Pointer converter);
	/**
	 * Original signature : <code>void wkhtmltoimage_destroy_converter(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:24</i>
	 */
	void wkhtmltoimage_destroy_converter(PointerByReference converter);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_warning_callback(wkhtmltoimage_converter*, wkhtmltoimage_str_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:26</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_set_warning_callback(PointerByReference, wkhtmltoimage_str_callback)} instead
	 */
	@Deprecated 
	void wkhtmltoimage_set_warning_callback(Pointer converter, wkhtmltoimage_str_callback cb);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_warning_callback(wkhtmltoimage_converter*, wkhtmltoimage_str_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:26</i>
	 */
	void wkhtmltoimage_set_warning_callback(PointerByReference converter, wkhtmltoimage_str_callback cb);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_error_callback(wkhtmltoimage_converter*, wkhtmltoimage_str_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:28</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_set_error_callback(PointerByReference, wkhtmltoimage_str_callback)} instead
	 */
	@Deprecated 
	void wkhtmltoimage_set_error_callback(Pointer converter, wkhtmltoimage_str_callback cb);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_error_callback(wkhtmltoimage_converter*, wkhtmltoimage_str_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:28</i>
	 */
	void wkhtmltoimage_set_error_callback(PointerByReference converter, wkhtmltoimage_str_callback cb);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_phase_changed_callback(wkhtmltoimage_converter*, wkhtmltoimage_void_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:30</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_set_phase_changed_callback(PointerByReference, wkhtmltoimage_void_callback)} instead
	 */
	@Deprecated 
	void wkhtmltoimage_set_phase_changed_callback(Pointer converter, wkhtmltoimage_void_callback cb);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_phase_changed_callback(wkhtmltoimage_converter*, wkhtmltoimage_void_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:30</i>
	 */
	void wkhtmltoimage_set_phase_changed_callback(PointerByReference converter, wkhtmltoimage_void_callback cb);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_progress_changed_callback(wkhtmltoimage_converter*, wkhtmltoimage_int_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:32</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_set_progress_changed_callback(PointerByReference, wkhtmltoimage_int_callback)} instead
	 */
	@Deprecated 
	void wkhtmltoimage_set_progress_changed_callback(Pointer converter, wkhtmltoimage_int_callback cb);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_progress_changed_callback(wkhtmltoimage_converter*, wkhtmltoimage_int_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:32</i>
	 */
	void wkhtmltoimage_set_progress_changed_callback(PointerByReference converter, wkhtmltoimage_int_callback cb);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_finished_callback(wkhtmltoimage_converter*, wkhtmltoimage_int_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:34</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_set_finished_callback(PointerByReference, wkhtmltoimage_int_callback)} instead
	 */
	@Deprecated 
	void wkhtmltoimage_set_finished_callback(Pointer converter, wkhtmltoimage_int_callback cb);
	/**
	 * Original signature : <code>void wkhtmltoimage_set_finished_callback(wkhtmltoimage_converter*, wkhtmltoimage_int_callback)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:34</i>
	 */
	void wkhtmltoimage_set_finished_callback(PointerByReference converter, wkhtmltoimage_int_callback cb);
	/**
	 * Original signature : <code>int wkhtmltoimage_convert(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:36</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_convert(PointerByReference)} instead
	 */
	@Deprecated 
	int wkhtmltoimage_convert(Pointer converter);
	/**
	 * Original signature : <code>int wkhtmltoimage_convert(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:36</i>
	 */
	int wkhtmltoimage_convert(PointerByReference converter);
	/**
	 * CAPI(void) wkhtmltoimage_cancel(wkhtmltoimage_converter * converter);<br>
	 * Original signature : <code>int wkhtmltoimage_current_phase(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:41</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_current_phase(PointerByReference)} instead
	 */
	@Deprecated 
	int wkhtmltoimage_current_phase(Pointer converter);
	/**
	 * CAPI(void) wkhtmltoimage_cancel(wkhtmltoimage_converter * converter);<br>
	 * Original signature : <code>int wkhtmltoimage_current_phase(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:41</i>
	 */
	int wkhtmltoimage_current_phase(PointerByReference converter);
	/**
	 * Original signature : <code>int wkhtmltoimage_phase_count(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:43</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_phase_count(PointerByReference)} instead
	 */
	@Deprecated 
	int wkhtmltoimage_phase_count(Pointer converter);
	/**
	 * Original signature : <code>int wkhtmltoimage_phase_count(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:43</i>
	 */
	int wkhtmltoimage_phase_count(PointerByReference converter);
	/**
	 * Original signature : <code>char* wkhtmltoimage_phase_description(wkhtmltoimage_converter*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:45</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_phase_description(PointerByReference, int)} instead
	 */
	@Deprecated 
	Pointer wkhtmltoimage_phase_description(Pointer converter, int phase);
	/**
	 * Original signature : <code>char* wkhtmltoimage_phase_description(wkhtmltoimage_converter*, int)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:45</i>
	 */
	Pointer wkhtmltoimage_phase_description(PointerByReference converter, int phase);
	/**
	 * Original signature : <code>char* wkhtmltoimage_progress_string(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:47</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_progress_string(PointerByReference)} instead
	 */
	@Deprecated 
	Pointer wkhtmltoimage_progress_string(Pointer converter);
	/**
	 * Original signature : <code>char* wkhtmltoimage_progress_string(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:47</i>
	 */
	Pointer wkhtmltoimage_progress_string(PointerByReference converter);
	/**
	 * Original signature : <code>int wkhtmltoimage_http_error_code(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:49</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_http_error_code(PointerByReference)} instead
	 */
	@Deprecated 
	int wkhtmltoimage_http_error_code(Pointer converter);
	/**
	 * Original signature : <code>int wkhtmltoimage_http_error_code(wkhtmltoimage_converter*)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:49</i>
	 */
	int wkhtmltoimage_http_error_code(PointerByReference converter);
	/**
	 * Original signature : <code>long wkhtmltoimage_get_output(wkhtmltoimage_converter*, const unsigned char**)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:51</i><br>
	 * @deprecated use the safer method {@link #wkhtmltoimage_get_output(PointerByReference, PointerByReference)} instead
	 */
	@Deprecated 
	NativeLong wkhtmltoimage_get_output(Pointer converter, PointerByReference charPtrPtr1);
	/**
	 * Original signature : <code>long wkhtmltoimage_get_output(wkhtmltoimage_converter*, const unsigned char**)</code><br>
	 * <i>native declaration : src/main/c/wkhtmltox/image.h:51</i>
	 */
	NativeLong wkhtmltoimage_get_output(PointerByReference converter, PointerByReference charPtrPtr1);
	public static class wkhtmltoimage_converter extends PointerType {
		public wkhtmltoimage_converter(Pointer address) {
			super(address);
		}
		public wkhtmltoimage_converter() {
			super();
		}
	};
	public static class wkhtmltoimage_global_settings extends PointerType {
		public wkhtmltoimage_global_settings(Pointer address) {
			super(address);
		}
		public wkhtmltoimage_global_settings() {
			super();
		}
	};
}
